const data = {
  product: [
    {
      name: 'Free Shirt',
      category: 'Shirts',
      image: '/images/sample.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStocke: 20,
      description: 'Any text',
    },
    {
      name: 'Free Shirt 1',
      category: 'Shirts',
      image: '/images/sample.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStocke: 20,
      description: 'Any text',
    },
    {
      name: 'Free Shirt 2',
      category: 'Shirts',
      image: '/images/sample.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStocke: 20,
      description: 'Any text',
    },
    {
      name: 'Free Shirt 3',
      category: 'Shirts',
      image: '/images/sample.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStocke: 20,
      description: 'Any text',
    },
    {
      name: 'Free Shirt 4',
      category: 'Shirts',
      image: '/images/sample.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStocke: 20,
      description: 'Any text',
    },
  ],
};

export default data;
